# nixpacks.toml

[phases.setup]
nixPkgs = ["python313", "gcc", "gfortran", "openblas"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "uvicorn src.server.app:app --host 0.0.0.0 --port $PORT"
